

name: Java Maven Build & Publish Artifact

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
  workflow_call:
    inputs:
      working-directory:
        description: working directory name
        type: string
        required: false
        default: '.'
    

jobs:
  build_test:

    runs-on: ubuntu-latest
    
    outputs:
      commit-id: ${{ steps.get_commit.outputs.commit_id }}
      
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    
    - name: Get Git commit ID
      id: get_commit
      run: echo "commit_id=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
    
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Print current directory
      run: pwd
    - name: Print current directory and contents
      run: |
        pwd
        ls -al
    - name: Print working-directory from input
      run: |
        echo "Working directory is: ${{ inputs.working-directory }}"
        cd ${{ inputs.working-directory }}
        pwd
        ls -al
    - name: Run tests
      run: mvn -B test --file pom.xml
      working-directory: ${{ inputs.working-directory }}

    - name: Upload test reports
      if: always()  # ensures it runs even if tests fail
      uses: actions/upload-artifact@v4
      with:
        name: surefire-reports
        path: ${{ inputs.working-directory }}/target/surefire-reports/
   
  publish-job:
    runs-on: ubuntu-latest
    needs: build_test
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - run: mvn --batch-mode --update-snapshots verify
    - run: mkdir staging && cp target/*.jar staging
    - uses: actions/upload-artifact@v4
      with:
        name: Package
        path: staging
